---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
refresh: 3000
target: _self
